# Your translations go here. To be used with the 'translate' liquid filter
# Example:
#   {{ 'hello_world' | translate }}
#

# hello_world:
#   en: Hello world !
#   fr: Bonjour le monde !

locales_de:
  de: Deutsch
  en: German

locales_en:
  de: Englisch
  en: English

button_back:
  de: Zur체ck
  en: Back

button_before:
  de: R체ckw채rts
  en: Before

button_next:
  de: Vorw채rts
  en: Next

zoom_out:
  de: "- zoom"
  en: "- zoom"

zoom_in:
  de: "zoom +"
  en: "zoom +"

sidebar_contact_title:
  de: Kontakt
  en: Contact

sidebar_institutes_title:
  de: Institute
  en: Institutes

sidebar_news_title:
  de: Aktuelles
  en: News

label_phone:
  de: Tel
  en: Tel

label_fax:
  de: Fax
  en: Fax

menu_institute_success_stories:
  de: Erfolge
  en: Success stories

menu_institute_success_stories_slug:
  de: erfolgsgeschichten
  en: success_stories

menu_institute_team:
  de: Team
  en: Team

menu_institute_news:
  de: Aktuelles
  en: News

navigation_loose_weight:
  de: Abnehmen
  en: Weight loss